# Generated by Django 3.1.6 on 2021-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_offer_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
